description: "Testing LangGraph routing agent"

providers:
  - "exec: npx tsx eval/ToolAgentEval.mts"

prompts:
  - "{{query}}"

tests:
  - vars:
      query: "Tell me a cat fact."
    options:
      provider: openai:gpt-4.1
    assert:
      - type: llm-rubric
        value: is a cat fact
